name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 198.38.87.182
          username: root
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            REPO_DIR="/home/skjbmd/public_html"

            # Check if .git exists, otherwise clone
            if [ ! -d "$REPO_DIR/.git" ]; then
              rm -rf $REPO_DIR
              git clone git@github.com:vatsalrishabh/skjbmd-express.git $REPO_DIR
            else
              cd $REPO_DIR
              git pull origin main
            fi

            cd $REPO_DIR
            npm install
            pm2 reload skjbmd.org --update-env
