name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 198.38.87.182        # Replace with your VPS IP
          username: root             # Or your VPS user
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Your SSH private key stored in GitHub Secrets
          script: |
            REPO_DIR="/home/skjbmd/public_html"
            if [ ! -d "$REPO_DIR" ]; then
              git clone git@github.com:vatsalrishabh/skjbmd-express.git $REPO_DIR
            else
              cd $REPO_DIR
              git pull origin main
            fi
            cd $REPO_DIR
            npm install
            pm2 reload skjbmd.org --update-env
