name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to VPS via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: 198.38.87.182        # Your VPS IP
          username: root             # Your VPS username (or 'skjbmd' if preferred)
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/skjbmd
            # Remove old folder to avoid partial updates
            rm -rf public_html
            # Clone fresh copy of your repo
            git clone git@github.com:vatsalrishabh/skjbmd.git public_html
            cd public_html
            npm install
            pm2 reload skjbmd.org
